Makefile, docker/docker-compose.local.yml, service/common-api/README.md, service/common-api/schema/migrations/20240120162119_add_vspo_common_table.sql, service/common-api/schema/query.sql, service/common-api/sqlc.yaml
Fixes #154 .
feat: define data model & setup sqlc+goose
=> feat: define data model & setup sqlc+goose

service/vspo-schedule/web/src/data/members.ts
New members have been added to VSPO! 🥳
https://twitter.com/kokage_tsumugi
With the addition of new members, we are adding them to the master data.
=> chore: add new member

.github/workflows/gcp_deploy.yml, deployment/modules/iam/locals.tf, deployment/modules/iam/main.tf, deployment/modules/iam/variables.tf
=> chore: add github action service account

.github/workflows/ci-terraform-blue.yml, Makefile, deployment/blue/main.tf
=> chore: add workload identity pool resource

service/vspo-schedule/web/src/data/members.ts
new vspo member 
https://twitter.com/yuuhi_sendo
=> add: new vspo member

.github/workflows/gcp_deploy.yml, deployment/blue/main.tf, deployment/modules/artifact_registry/output.tf, deployment/modules/cloud_run/locals.tf, deployment/modules/cloud_run/main.tf, deployment/modules/cloud_run/variables.tf
=> fix: cloud scheduler target

.github/workflows/dependabot-auto-merge.yml
=> chore: fix auto merge

.github/workflows/gcp_deploy.yml
=> fix(ci): deploy cloud run

.github/workflows/gcp_deploy.yml, deployment/modules/iam/main.tf
=> fix: github service account role

deployment/terraform/blue/main.tf, deployment/terraform/modules/cloud_scheduler_job/main.tf
https://www.googlecloudcommunity.com/gc/Integration-Services/INVALID-ARGUMENT-occurs-when-trying-to-pass-request-body-from/m-p/741854#M1150
=> fix: encode

service/vspo-schedule/web/src/pages/schedule/[status].tsx
Include the title and metadata description of the latest livestream.
=> fix: top page metadata

.github/workflows/deploy-workers.yaml
=> fix: working directory

service/vspo-schedule/web/src/data/members.ts
=> Add New EN Member🍾

service/vspo-schedule/proxy/pkg/processor/event.ts, service/vspo-schedule/proxy/pkg/processor/video.ts, service/vspo-schedule/proxy/routes.ts, service/vspo-schedule/proxy/schema.ts, service/vspo-schedule/web/scripts/vercel-ignore-build-step.sh, service/vspo-schedule/web/src/lib/api.ts, service/vspo-schedule/web/src/lib/utils.ts, service/vspo-schedule/web/src/pages/clips.tsx, service/vspo-schedule/web/src/pages/events/[yearMonth].tsx, service/vspo-schedule/web/src/pages/events/details/[id].tsx, service/vspo-schedule/web/src/pages/freechat.tsx, service/vspo-schedule/web/src/pages/schedule/[status].tsx, service/vspo-schedule/web/src/pages/site-news/[id].tsx, service/vspo-schedule/web/src/pages/twitch-clips.tsx
=> bugfix: proxy(twitch clip fetch)

service/vspo-schedule/proxy/pkg/middleware/init.ts, service/vspo-schedule/proxy/routes.ts
=> bugfix(proxy): req parameter handling

service/vspo-schedule/web/next-sitemap.config.js, service/vspo-schedule/web/package.json, service/vspo-schedule/web/pnpm-lock.yaml, service/vspo-schedule/web/src/components/Elements/Card/LivestreamCard.tsx, service/vspo-schedule/web/src/components/Elements/Google/GoogleAnalytics.tsx, service/vspo-schedule/web/src/components/Elements/Modal/VideoModal.tsx, service/vspo-schedule/web/src/components/Layout/Footer.tsx, service/vspo-schedule/web/src/components/Templates/Livestreams.tsx, service/vspo-schedule/web/src/components/Templates/RelatedVideos.tsx, service/vspo-schedule/web/src/constants/navigation.ts, service/vspo-schedule/web/src/data/mocks/clips.ts, service/vspo-schedule/web/src/data/mocks/livestreams.ts, service/vspo-schedule/web/src/lib/dayjs/dayjs.ts, service/vspo-schedule/web/src/lib/dayjs/index.ts, service/vspo-schedule/web/src/lib/utils.ts, service/vspo-schedule/web/src/pages/clips.tsx, service/vspo-schedule/web/src/pages/events/[yearMonth].tsx, service/vspo-schedule/web/src/pages/events/details/[id].tsx, service/vspo-schedule/web/src/pages/freechat.tsx, service/vspo-schedule/web/src/pages/schedule/[status].tsx, service/vspo-schedule/web/src/pages/twitch-clips.tsx, service/vspo-schedule/web/src/types/streaming.ts
=> feat: Set default time zones based on selected language

service/vspo-schedule/web/src/pages/api/relatedVideo.ts, service/vspo-schedule/web/src/pages/clips.tsx, service/vspo-schedule/web/src/pages/twitch-clips.tsx
Fixes # [insert GH or internal issue number(s)].
=> remove: revalidate

.github/dependabot.yml
Because frequent notifications are noisy, I will adjust the interval.
I'll probably replace it with Renovate later, which can likely group them.
=> temp: fix interval

service/vspo-schedule/web/pnpm-lock.yaml
=> fix: lockfile

.github/workflows/ci-vspo-schedule-web.yaml, service/vspo-schedule/web/package.json, service/vspo-schedule/web/pnpm-lock.yaml
- downgrade `mui/lab`
- add code check ci
=> fix: @mui/lab deps

.gitignore, service/cron/.gitignore, service/cron/infra/database/schema/migration/20240710170657_insert_member.sql, service/cron/local/compose.local.yml, service/cron/usecase/video_impl.go, service/cron/vercel.json
#154 
I deployed the cron and will gradually replace it with the Discord bot while monitoring the situation in the background.
=> fix: cron handling

service/vspo-schedule/web/src/pages/events/[yearMonth].tsx
Fixes [issue 491](https://github.com/sugar-cat7/vspo-portal/issues/491).
=> Fix events date size on reduced devices

service/vspo-schedule/web/src/components/Elements/Modal/VideoModal.tsx
Fixes [488 BUG: VideoModal is unaffected by browser forward/back buttons](https://github.com/sugar-cat7/vspo-portal/issues/488).
=> fix: VideoModal is unaffected by browser forward/back buttons

service/vspo-schedule/proxy/pkg/translator/index.ts
=> bugfix(proxy): The translated title is displayed in JSON Format

service/vspo-schedule/proxy/pkg/translator/index.ts
=> bugfix(proxy): translate

service/vspo-schedule/proxy/pkg/processor/event.ts
=> bugfix(proxy): event translate

.github/workflows/ci-vspo-schedule-web.yaml
=> chore(ci): remove --frozen-lockfile

service/vspo-schedule/web/public/locales/en/common.json, service/vspo-schedule/web/public/locales/ja/common.json, service/vspo-schedule/web/src/components/Layout/ContentLayout.tsx
=> feat(web): update alert

service/vspo-schedule/proxy/routes.ts, service/vspo-schedule/web/src/components/Elements/Drawer/Drawer.tsx, service/vspo-schedule/web/src/components/Elements/Modal/VideoModal.tsx, service/vspo-schedule/web/src/components/Layout/Footer.tsx, service/vspo-schedule/web/src/components/Layout/Header.tsx, service/vspo-schedule/web/src/components/Layout/Navigation.tsx, service/vspo-schedule/web/src/components/Templates/Livestreams.tsx, service/vspo-schedule/web/src/constants/navigation.ts, service/vspo-schedule/web/src/middleware.ts, service/vspo-schedule/web/src/pages/schedule/[status].tsx
Reverts sugar-cat7/vspo-portal#533
=> Revert "fix(web): disable middleware cache to force getServerSideProps"

service/vspo-schedule/proxy/cmd/server/index.ts
Reverts sugar-cat7/vspo-portal#559
=> Revert "fix(proxy):  middleware cache"

service/vspo-schedule/web/src/data/members.ts
=> chore: update image

deployment/terraform/modules/cloud_scheduler_job/main.tf
=> fix: scheduler

service/vspo-schedule/web/src/data/members.ts
https://x.com/kokage_tsumugi/status/1855246635967906006
=> chore: add twich id

.github/workflows/deploy-server-workers.yaml
https://github.com/sugar-cat7/vspo-portal/actions/runs/13038556114/job/36374824767
=> chore: add pnpm/action-setup

service/server/config/wrangler/vspo-portal-app/wrangler.toml, service/server/config/wrangler/vspo-portal-cron/wrangler.toml, service/server/config/wrangler/vspo-portal-gateway/wrangler.toml, service/server/infra/discord/command/index.ts
=> chore(config): add cloudflare logs

.github/workflows/deploy-server-workers.yaml
=> chore: add SENTRY_DSN

service/server/config/wrangler/vspo-portal-cron/wrangler.toml
=> chore(job): fix cron schedule

service/server/domain/video.ts
=> chore(discord job): fix twitch thumbnail

service/server/cmd/server/gateway.ts, service/server/cmd/server/internal/application/index.ts, service/server/config/env/api.ts, service/server/config/env/flag.ts, service/server/config/env/internal.ts, service/server/config/featureFlag/index.ts, service/server/domain/discord.ts, service/server/domain/service/discord.ts, service/server/infra/discord/command/index.ts, service/server/infra/http/trace/cloudflare.ts, service/server/infra/http/workflow/channel/trasnlate.ts, service/server/infra/http/workflow/video/trasnlate.ts, service/server/infra/repository/creator.ts, service/server/infra/repository/discord.ts, service/server/infra/repository/video.ts, service/server/infra/youtube/index.ts, service/server/package.json, service/server/pkg/logging/index.ts, service/server/pnpm-lock.yaml, service/server/usecase/discord.ts, service/server/usecase/video.ts
=> fix: discord job bug

service/server/cmd/server/internal/application/index.ts, service/server/domain/service/video.ts, service/server/infra/repository/video.ts, service/server/infra/youtube/index.ts
- Since it contains UTF-8, apply `encodeComponent`.  
- Compute the diff and enqueue it.  
- `enqueue` has a maximum limit of 100 messages.
=> fix(job): fetch youtube videos

service/server/cmd/cron/index.ts
=> chore(discord): add feature flag

service/server/config/featureFlag/index.ts
Fixes # [insert GH or internal issue number(s)].
=> chore: fix typo

.github/workflows/deploy-server-workers.yaml, service/server/infra/http/hono/middleware/init.ts, service/server/vitest.config.ts
Fixes # [insert GH or internal issue number(s)].
=> dev -> main

service/server/cmd/cron/index.ts, service/server/cmd/server/gateway.ts, service/server/cmd/server/internal/application/index.ts, service/server/config/wrangler/prd/vspo-portal-cron/wrangler.toml, service/server/docs/domain_model.md, service/server/domain/event.ts, service/server/infra/dependency/index.ts, service/server/infra/http/routes/event.ts, service/server/infra/http/routes/schema/clip.ts, service/server/infra/http/routes/schema/event.ts, service/server/infra/repository/event.ts, service/server/infra/repository/index.ts, service/server/infra/repository/schema/index.ts, service/server/infra/repository/schema/migrations/0003_flowery_spiral.sql, service/server/infra/repository/schema/migrations/meta/0003_snapshot.json, service/server/infra/repository/schema/migrations/meta/_journal.json, service/server/infra/storage/index.ts, service/server/usecase/event.ts, service/server/usecase/index.ts
up to the storage of metadata
https://github.com/sugar-cat7/vspo-portal/issues/674
=> feat(server): add vspo content

service/vspo-schedule/v2/web/src/features/shared/components/Elements/Google/GoogleAnalytics.tsx, service/vspo-schedule/v2/web/src/features/shared/components/Layout/ContentLayout.tsx
- google analytics
- remove ads
=> chore: fix google tags

service/vspo-schedule/v2/web/src/features/schedule/pages/ScheduleStatus/components/DateSearchDialog.tsx
=> remove: button
